CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(50) NULL DEFAULT NULL,
	`birth_day` DATE NULL DEFAULT NULL,
	`sex` VARCHAR(2) NULL DEFAULT NULL,
	`address` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=26
;
